USE [master]
GO
/****** Object:  Database [DEMO]    Script Date: 12-11-2023 18:41:47 ******/
CREATE DATABASE [DEMO]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DEMO', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\DEMO.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DEMO_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\DEMO_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [DEMO] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DEMO].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [DEMO] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [DEMO] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [DEMO] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [DEMO] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [DEMO] SET ARITHABORT OFF 
GO
ALTER DATABASE [DEMO] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [DEMO] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [DEMO] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [DEMO] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [DEMO] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [DEMO] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [DEMO] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [DEMO] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [DEMO] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [DEMO] SET  DISABLE_BROKER 
GO
ALTER DATABASE [DEMO] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [DEMO] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [DEMO] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [DEMO] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [DEMO] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [DEMO] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [DEMO] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [DEMO] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [DEMO] SET  MULTI_USER 
GO
ALTER DATABASE [DEMO] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [DEMO] SET DB_CHAINING OFF 
GO
ALTER DATABASE [DEMO] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [DEMO] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [DEMO] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [DEMO] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [DEMO] SET QUERY_STORE = ON
GO
ALTER DATABASE [DEMO] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [DEMO]
GO
/****** Object:  Table [dbo].[Children]    Script Date: 12-11-2023 18:41:47 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Children](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
	[Description] [nvarchar](50) NULL,
 CONSTRAINT [PK_Children] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [IX_Children] UNIQUE NONCLUSTERED 
(
	[Name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[GrandParents]    Script Date: 12-11-2023 18:41:47 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[GrandParents](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
	[Description] [nvarchar](50) NULL,
	[PrimaryChild] [int] NOT NULL,
 CONSTRAINT [PK_GrandParents] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Parents]    Script Date: 12-11-2023 18:41:47 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Parents](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
	[Description] [nvarchar](50) NULL,
	[GrandParentID] [int] NULL,
 CONSTRAINT [PK_Parent] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [IX_Parents] UNIQUE NONCLUSTERED 
(
	[Name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ParentsChildren]    Script Date: 12-11-2023 18:41:47 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ParentsChildren](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ParentID] [int] NOT NULL,
	[ChildID] [int] NOT NULL,
 CONSTRAINT [PK_ParentsChildren] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IX_GrandParents]    Script Date: 12-11-2023 18:41:47 ******/
CREATE UNIQUE NONCLUSTERED INDEX [IX_GrandParents] ON [dbo].[GrandParents]
(
	[Name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Parents]  WITH CHECK ADD  CONSTRAINT [FK_Parents_GrandParents] FOREIGN KEY([GrandParentID])
REFERENCES [dbo].[GrandParents] ([ID])
GO
ALTER TABLE [dbo].[Parents] CHECK CONSTRAINT [FK_Parents_GrandParents]
GO
ALTER TABLE [dbo].[Parents]  WITH CHECK ADD  CONSTRAINT [FK_Parents_Parents] FOREIGN KEY([ID])
REFERENCES [dbo].[Parents] ([ID])
GO
ALTER TABLE [dbo].[Parents] CHECK CONSTRAINT [FK_Parents_Parents]
GO
USE [master]
GO
ALTER DATABASE [DEMO] SET  READ_WRITE 
GO
